name: Generate Mermaid Graph

on:
  push:
    branches: [ main ]
    paths:
      - 'images.json'
      - 'groups.json'
      - 'generateMermaidCode.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install mermaid-cli
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Generate .mmd and SVG
        run: |
          node generateMermaidCode.js > graph.mmd
          mkdir -p docs
          mmdc -i graph.mmd -o docs/graph.svg

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add graph.mmd docs/graph.svg
          git commit -m "chore: auto-generate graph.svg" || echo "no changes"
          git push
